"""AFDM Tx/Rx primitives: DAFT, IDAFT, chirp-periodic prefix.

An AFDM block is generated by applying the IDAFT to a data vector, prepending a
chirp-periodic prefix (CPP), transmitting through the doubly-dispersive channel,
stripping the prefix, and applying the DAFT at the receiver.

The DAFT with parameters (c_1, c_2) is the unitary map
    F_{c_1,c_2}(x)[k] = (1/sqrt(N)) sum_n x[n] exp(-j 2 pi (c_2 k^2 + kn/N + c_1 n^2)),
factored as F_{c_1,c_2} = D_{c_2}^* F D_{c_1}^*, where F is the DFT and
D_c = diag(exp(j 2 pi c n^2)).
"""

from __future__ import annotations

from dataclasses import dataclass

import torch


@dataclass
class AFDMSystem:
    """Chirp parameters and Tx/Rx primitives for an N-subcarrier AFDM block.

    Parameters
    ----------
    N        : number of subcarriers (must be even for c_1 in \eqref{eq:c1_correct} to
               make the chirp-periodic prefix reduce to an ordinary cyclic prefix).
    kappa_max: maximum integer Doppler index; sets c_1 per Bemani et al. 2023.
    ell_max  : maximum integer delay index (bounds the required cyclic prefix length).
    c1       : chirp-1 parameter; if None, uses (2 kappa_max + 1) / (2 N).
    c2       : chirp-2 parameter; if None, uses 1 / (2 N).
    device   : torch device.
    dtype    : complex dtype (default torch.complex64).
    """

    N: int
    kappa_max: int
    ell_max: int
    c1: float | None = None
    c2: float | None = None
    device: str | torch.device = "cuda:0"
    dtype: torch.dtype = torch.complex64

    def __post_init__(self) -> None:
        assert self.N % 2 == 0, "N must be even so 2Nc1 is an integer for standard CPP-to-CP reduction."
        if self.c1 is None:
            self.c1 = (2 * self.kappa_max + 1) / (2 * self.N)
        if self.c2 is None:
            self.c2 = 1.0 / (2 * self.N)
        # Chirp diagonal phasors, precomputed on device.
        n = torch.arange(self.N, device=self.device, dtype=torch.float32)
        two_pi = 2.0 * torch.pi
        # exp(+j 2 pi c n^2) is D_c on the diagonal; its conjugate is D_c^*.
        self._Dc1_diag = torch.exp(1j * two_pi * self.c1 * n * n).to(self.dtype)
        self._Dc2_diag = torch.exp(1j * two_pi * self.c2 * n * n).to(self.dtype)
        # Real dtype matching self.dtype for internal FFT reals.
        self._rdtype = torch.float32 if self.dtype == torch.complex64 else torch.float64
        # Verify design: 2 N c1 should be an integer near 2 kappa_max + 1.
        assert abs(2 * self.N * self.c1 - round(2 * self.N * self.c1)) < 1e-9, (
            "2 N c1 must be an integer for CPP -> ordinary CP reduction."
        )

    # ------------------------------------------------------------------
    # DAFT / IDAFT
    # ------------------------------------------------------------------
    def idaft(self, x: torch.Tensor) -> torch.Tensor:
        """Apply the IDAFT F^{-1} = D_{c1} F^H D_{c2} to input x of shape (..., N).

        Preserves batch dimensions.
        """
        assert x.shape[-1] == self.N
        # D_{c2} x: pre-multiply by the c2 chirp phasor
        z = x * self._Dc2_diag
        # F^H z: inverse DFT (with 1/sqrt(N) normalization)
        z = torch.fft.ifft(z, dim=-1, norm="ortho")
        # D_{c1} : post-multiply by the c1 chirp phasor
        z = z * self._Dc1_diag
        return z

    def daft(self, r: torch.Tensor) -> torch.Tensor:
        """Apply the DAFT F = D_{c2}^* F D_{c1}^* to time-domain signal r of shape (..., N)."""
        assert r.shape[-1] == self.N
        # D_{c1}^* r
        z = r * torch.conj(self._Dc1_diag)
        # F z : forward DFT (with 1/sqrt(N) normalization)
        z = torch.fft.fft(z, dim=-1, norm="ortho")
        # D_{c2}^*
        z = z * torch.conj(self._Dc2_diag)
        return z

    # ------------------------------------------------------------------
    # Chirp-periodic prefix (reduces to ordinary CP under our design)
    # ------------------------------------------------------------------
    def add_prefix(self, s: torch.Tensor, N_cp: int | None = None) -> torch.Tensor:
        """Prepend the chirp-periodic prefix.

        Under our design (2 N c1 integer, N even), the CPP simplifies to an
        ordinary cyclic prefix: s[-n] = s[N - n], n = 1, ..., N_cp.
        See eq. (6)-(7) in the paper.
        """
        if N_cp is None:
            N_cp = self.ell_max
        assert N_cp >= self.ell_max, (
            f"CP length ({N_cp}) must be >= max delay ({self.ell_max})."
        )
        assert s.shape[-1] == self.N
        prefix = s[..., self.N - N_cp:]  # ordinary cyclic prefix
        return torch.cat([prefix, s], dim=-1)

    def remove_prefix(self, r_with_cp: torch.Tensor, N_cp: int | None = None) -> torch.Tensor:
        """Strip the prefix from a received signal."""
        if N_cp is None:
            N_cp = self.ell_max
        return r_with_cp[..., N_cp:]

    # ------------------------------------------------------------------
    # Utilities
    # ------------------------------------------------------------------
    def unitary_error_fro(self) -> torch.Tensor:
        """Return ||F^H F - I||_F, a check of DAFT unitarity."""
        eye = torch.eye(self.N, device=self.device, dtype=self.dtype)
        FhF = self.daft(self.idaft(eye))  # apply DAFT to columns of F^{-1}(I) = F^{-1}
        # For unitarity we should have F F^{-1} = I.
        return torch.norm(FhF - eye, p="fro")

    def daft_matrix(self) -> torch.Tensor:
        """Return the explicit N x N DAFT matrix F such that y = F @ x when x is a column vector.

        Useful for verification; not for production use.
        """
        # daft(eye) with eye of shape (N,N) applies DAFT to each row, so row i of the
        # output is DAFT(e_i) = column i of F. So we must transpose to get F.
        return self.daft(torch.eye(self.N, device=self.device, dtype=self.dtype)).T.contiguous()

    def __repr__(self) -> str:
        return (
            f"AFDMSystem(N={self.N}, kappa_max={self.kappa_max}, "
            f"ell_max={self.ell_max}, c1={self.c1:.6f}, c2={self.c2:.6f}, "
            f"device={self.device}, 2Nc1={round(2 * self.N * self.c1)})"
        )
